config setup
    uniqueids=no

conn FC_Base
    keyexchange=ikev1
    aggressive=yes
    authby=xauthpsk
    xauth=client
    left=%defaultroute
    leftid=FC_Linux
    leftsourceip=%config
    #leftauth=psk
    #leftauth2=xauth
    right=IP_PUBLICA_DEL_FG
    rightid=%any
    rightsubnet=0.0.0.0/0
    ike=aes128-sha256-modp2048,aes256-sha256-modp2048,aes128-sha1-modp2048,aes256-sha1-modp2048
    esp=aes256-sha256-modp2048,aes128-sha1-modp2048
    modeconfig=pull
    xauth_identity=kiara.arosemena

conn FC_Linux
    also=FC_Base
    rightsubnet=192.168.10.0/23
    auto=add

conn FC_Red172
    also=FC_Base
    rightsubnet=172.30.20.0/24
    auto=add
