#version: "3.8"

services:
  freepbx-db:
    image: mariadb:10.11
    container_name: maria-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "Sup3rp4s5*!"
      MYSQL_DATABASE: freepbx
      MYSQL_USER: freepbxuser
      MYSQL_PASSWORD: "Fr33us3rpbx."
      TZ: America/Panama
    volumes:
      - ./db-data:/var/lib/mysql

  freepbx:
    image: tiredofit/freepbx:latest
    container_name: freepbx
    depends_on:
      - freepbx-db
    restart: unless-stopped
    environment:
      DB_EMBEDDED: "FALSE"          # ← fuerza DB externa
      DB_HOST: freepbx-db           # ← nombre del servicio (DNS interno)
      DB_NAME: freepbx
      DB_USER: freepbxuser
      DB_PASS: "Fr33us3rpbx."
      RTP_START: "18000"
      RTP_FINISH: "18100"
      ENABLE_TLS: "TRUE"
      VIRTUALHOST: "pbx.local"
      TZ: America/Panama
    ports:
      - "8081:80"
      - "8443:443"
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5160:5160/udp"
      - "18000-18100:18000-18100/udp"
    volumes:
      - ./certs:/etc/apache2/certs
      - ./data:/var/www/html/admin/templates_cache
      - ./logs:/var/log
      - ./asterisk-etc:/etc/asterisk
      - ./asterisk-lib:/var/lib/asterisk
      - ./asterisk-spool:/var/spool/asterisk
      - ./recordings:/var/spool/asterisk/monitor
      - ./backups:/var/spool/asterisk/backup