services:
  ocsinventory:
    image: ocsinventory/ocsinventory-docker-image:2.12.3
    container_name: ocs-inventory
    restart: always
    networks:
      - mi-red

    ports:
      - "8080:80"     # HTTP  -> http://NAS:8080/ocsreports
      - "8843:443"    # HTTPS -> https://NAS:8443/ocsreports
      
    devices:
      - /dev/urandom:/dev/urandom
      - /dev/random:/dev/random

    environment:
      TZ: America/Panama
      OCS_DB_SERVER: maria-db  # 🔒 cámbialo si usas otro host o contenedor
      OCS_DB_PORT: "3306"
      OCS_DB_NAME: ocsweb
      OCS_DB_USER: ocs
      OCS_DB_PASS: ocs24cfe
   
    volumes:
      - ./ocs-data:/var/lib/ocsinventory-reports # 🔒 crear este volumen manualmente
      - ./ocs-logs:/var/log/ocsinventory-server  # 🔒 crear este volumen manualmente

networks:
  mi-red:
    external: true # 🔒 importante si la red ya existe
